marccode = {"afr": "Afrikaans",
"alb": "Albanian",
"amh": "Amharic",
"ara": "Arabic",
"arm": "Armenian",
"aze": "Azerbaijani",
"ben": "Bengali",
"bos": "Bosnian",
"bul": "Bulgarian",
"cat": "Catalan",
"chi": "Chinese",
"cze": "Czech",
"dan": "Danish",
"dut": "Dutch",
"eng": "English",
"epo": "Esperanto",
"est": "Estonian",
"fin": "Finnish",
"fre": "French",
"geo": "Georgian",
"ger": "German",
"gla": "Scottish Gaelic",
"gre": "modern Greek",
"heb": "Hebrew",
"hin": "Hindi",
"hrv": "Croatian",
"hun": "Hungarian",
"ice": "Icelandic",
"ind": "Indonesian",
"ita": "Italian",
"jpn": "Japanese",
"kin": "Kinyarwanda",
"kor": "Korean",
"lat": "Latin",
"lav": "Latvian",
"lit": "Lithuanian",
"mac": "Macedonian",
"mal": "Malayalam",
"mao": "Maori",
"may": "Malay",
"mul": "multiple languages",
"nor": "Norwegian",
"per": "Persian or Iranian",
"pol": "Polish",
"por": "Portuguese",
"pus": "Pushto",
"rum": "Romanian or Moldovan",
"rus": "Russian",
"san": "Sanskrit",
"slo": "Slovak",
"slv": "Slovenian",
"spa": "Spanish",
"srp": "Serbian",
"swe": "Swedish",
"tha": "Thai",
"tur": "Turkish",
"ukr": "Ukrainian",
"und": "undetermined language",
"urd": "Urdu",
"vie": "Vietnamese",
"wel": "Welsh"}
